### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib' How to use?

### ISSUE THREAD

**Issue by bulletproof2k** [Ahmedazim7804/traktstats#2]
In which file should I enter the values?

TMDB_API_KEY="value-here" 
TRAKT_API_KEY="value-here"

E:\DEV\Py\traktstats>python ui.py
Traceback (most recent call last):
  File "E:\DEV\Py\traktstats\ui.py", line 2, in <module>
    import crew_page
  File "E:\DEV\Py\traktstats\crew_page.py", line 1, in <module>
    import parseData
  File "E:\DEV\Py\traktstats\parseData.py", line 8, in <module>
    from bubblechart import BubbleChart
  File "E:\DEV\Py\traktstats\bubblechart.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

**Comment by Ahmedazim7804** [comment]
did you install requirements from requirement.txt file? if not do `pip install -r requirements.txt`

**Comment by bulletproof2k** [comment]
> did you install requirements from requirement.txt file? if not do `pip install -r requirements.txt`

Immediately set, where to enter api keys?

**Comment by Ahmedazim7804** [comment]
you can set it in getData.py file 
`tmdb.api_key = tmdb_API_KEY = os.environ['TMDB_API_KEY']`
`trakt_CLIENT_ID = os.environ['TRAKT_API_KEY']`
set it like 
`tmdb.api_key = tmdb_API_KEY = "your key"`
`trakt_CLIENT_ID = "your key"`

**Comment by bulletproof2k** [comment]
> you can set it in [getData.py](http://getData.py) file `tmdb.api_key = tmdb_API_KEY = os.environ['TMDB_API_KEY']` `trakt_CLIENT_ID = os.environ['TRAKT_API_KEY']` set it like `tmdb.api_key = tmdb_API_KEY = "your key"` `trakt_CLIENT_ID = "your key"`

tmdb.api_key = tmdb_API_KEY = os.environ['**MY_API_KEY**']
trakt_CLIENT_ID = os.environ['**MY_API_KEY**']

Did I understand you correctly?

**Comment by Ahmedazim7804** [comment]
No remove the os.environ line, and just put your key in simple string
`trakt_CLIENT_ID = "1283ff789sdf"` #whatever the key is

**Comment by bulletproof2k** [comment]
> No remove the os.environ line, and just put your key in simple string `trakt_CLIENT_ID = "1283ff789sdf"` #whatever the key is

Here is this line:
```
tmdb = TMDb()
tmdb.api_key = tmdb_API_KEY = os.environ['TMDB_API_KEY']
trakt_CLIENT_ID = os.environ['TRAKT_API_KEY']
```
Show by example in which simple and where exactly I have to enter api keys!?

**Comment by Ahmedazim7804** [comment]
`tmdb = TMDb()`
`tmdb.api_key = tmdb_API_KEY = 'YOUR KEY'`
`trakt_CLIENT_ID = 'YOUR KEY'`

like this

**Comment by bulletproof2k** [comment]
File:

```
tmdb = TMDb()
tmdb.api_key = tmdb_API_KEY = os.environ['TMDB_API_KEY']
trakt_CLIENT_ID = os.environ['TRAKT_API_KEY']
```

The next line in this file that I enter myself:

```
tmdb = TMDb()
tmdb.api_key = tmdb_API_KEY = 'YOUR KEY'
trakt_CLIENT_ID = 'YOUR KEY'
```

???

**Comment by bulletproof2k** [comment]
> `tmdb = TMDb()` `tmdb.api_key = tmdb_API_KEY = 'YOUR KEY'` `trakt_CLIENT_ID = 'YOUR KEY'`
> 
> like this

Where are these lines I asked you to add them to the file myself on getData.py right after those lines that you said not to touch ??? 🤦‍♂️

**Comment by Ahmedazim7804** [comment]
> File:
> 
> ```
> tmdb = TMDb()
> tmdb.api_key = tmdb_API_KEY = os.environ['TMDB_API_KEY']
> trakt_CLIENT_ID = os.environ['TRAKT_API_KEY']
> ```
> 
> The next line in this file that I enter myself:
> 
> ```
> tmdb = TMDb()
> tmdb.api_key = tmdb_API_KEY = 'YOUR KEY'
> trakt_CLIENT_ID = 'YOUR KEY'
> ```
> 
> ???

Why are you adding your lines???

Just replace these in getData.py file
`tmdb.api_key = tmdb_API_KEY = os.environ['TMDB_API_KEY']`
`trakt_CLIENT_ID = os.environ['TRAKT_API_KEY']`
to these
`tmdb.api_key = tmdb_API_KEY = 'YOUR KEY'`
`trakt_CLIENT_ID = 'YOUR KEY'`

and you have to add YOUR OWN API keys in place of "your api" text.

**Comment by bulletproof2k** [comment]
Here is your file, enter this there: "111111", "222222" (as if these are api keys)
[ui.txt](https://github.com/Ahmedazim7804/traktstats/files/13167624/ui.txt)

**Comment by bulletproof2k** [comment]
> > File:
> > ```
> > tmdb = TMDb()
> > tmdb.api_key = tmdb_API_KEY = os.environ['TMDB_API_KEY']
> > trakt_CLIENT_ID = os.environ['TRAKT_API_KEY']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The next line in this file that I enter myself:
> > ```
> > tmdb = TMDb()
> > tmdb.api_key = tmdb_API_KEY = 'YOUR KEY'
> > trakt_CLIENT_ID = 'YOUR KEY'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ???
> 
> Why are you adding your lines???
> 
> Just replace these in [getData.py](http://getData.py) file `tmdb.api_key = tmdb_API_KEY = os.environ['TMDB_API_KEY']` `trakt_CLIENT_ID = os.environ['TRAKT_API_KEY']` to these `tmdb.api_key = tmdb_API_KEY = 'YOUR KEY'` `trakt_CLIENT_ID = 'YOUR KEY'`
> 
> and you have to add YOUR OWN API keys in place of "your api" text.

```
E:\DEV\Py\traktstats>python ui.py
Traceback (most recent call last):
  File "E:\DEV\Py\traktstats\ui.py", line 2, in <module>
    import crew_page
  File "E:\DEV\Py\traktstats\crew_page.py", line 1, in <module>
    import parseData
  File "E:\DEV\Py\traktstats\parseData.py", line 11, in <module>
    from getData import getData, download_tmdb_image
  File "E:\DEV\Py\traktstats\getData.py", line 21, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
```

**Comment by bulletproof2k** [comment]
> > File:
> > ```
> > tmdb = TMDb()
> > tmdb.api_key = tmdb_API_KEY = os.environ['TMDB_API_KEY']
> > trakt_CLIENT_ID = os.environ['TRAKT_API_KEY']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The next line in this file that I enter myself:
> > ```
> > tmdb = TMDb()
> > tmdb.api_key = tmdb_API_KEY = 'YOUR KEY'
> > trakt_CLIENT_ID = 'YOUR KEY'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ???
> 
> Why are you adding your lines???
> 
> Just replace these in [getData.py](http://getData.py) file `tmdb.api_key = tmdb_API_KEY = os.environ['TMDB_API_KEY']` `trakt_CLIENT_ID = os.environ['TRAKT_API_KEY']` to these `tmdb.api_key = tmdb_API_KEY = 'YOUR KEY'` `trakt_CLIENT_ID = 'YOUR KEY'`
> 
> and you have to add YOUR OWN API keys in place of "your api" text.

E:\DEV\Py\traktstats>python ui.py
Traceback (most recent call last):
  File "E:\DEV\Py\traktstats\ui.py", line 2, in <module>
    import crew_page
  File "E:\DEV\Py\traktstats\crew_page.py", line 1, in <module>
    import parseData
  File "E:\DEV\Py\traktstats\parseData.py", line 11, in <module>
    from getData import getData, download_tmdb_image
  File "E:\DEV\Py\traktstats\getData.py", line 21, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

**Comment by Ahmedazim7804** [comment]
You have to install requirements from requirement.txt file.
do `pip install -r requirements.txt` in project dir.

**Comment by bulletproof2k** [comment]
> You have to install requirements from requirement.txt file. do `pip install -r requirements.txt` in project dir.

YEP

Traceback (most recent call last):
  File "E:\DEV\Py\traktstats\ui.py", line 2, in <module>
    import crew_page
  File "E:\DEV\Py\traktstats\crew_page.py", line 1, in <module>
    import parseData
  File "E:\DEV\Py\traktstats\parseData.py", line 11, in <module>
    from getData import getData, download_tmdb_image
  File "E:\DEV\Py\traktstats\getData.py", line 31, in <module>
    tmdb.api_key = tmdb_API_KEY = os.environ['MY_API_KEY']
                                  ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File frozen os, line 679, in __getitem__
KeyError: 'MY_API_KEY'

**File  frozen os, line 679, in __getitem__**

**Comment by bulletproof2k** [comment]
File "<frozen os>", line 679, in __getitem__
